// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MessageProto.proto
// Protobuf Java Version: 4.27.3

package org.gtpvpair.message;

public final class ExchangeProtoMessage {
  private ExchangeProtoMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ExchangeProtoMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:exchange_message_def.ProtMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>required string source_ip = 2;</code>
     * @return Whether the sourceIp field is set.
     */
    boolean hasSourceIp();
    /**
     * <code>required string source_ip = 2;</code>
     * @return The sourceIp.
     */
    java.lang.String getSourceIp();
    /**
     * <code>required string source_ip = 2;</code>
     * @return The bytes for sourceIp.
     */
    com.google.protobuf.ByteString
        getSourceIpBytes();

    /**
     * <code>required string dest_ip = 3;</code>
     * @return Whether the destIp field is set.
     */
    boolean hasDestIp();
    /**
     * <code>required string dest_ip = 3;</code>
     * @return The destIp.
     */
    java.lang.String getDestIp();
    /**
     * <code>required string dest_ip = 3;</code>
     * @return The bytes for destIp.
     */
    com.google.protobuf.ByteString
        getDestIpBytes();

    /**
     * <code>required string message_type = 4;</code>
     * @return Whether the messageType field is set.
     */
    boolean hasMessageType();
    /**
     * <code>required string message_type = 4;</code>
     * @return The messageType.
     */
    java.lang.String getMessageType();
    /**
     * <code>required string message_type = 4;</code>
     * @return The bytes for messageType.
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>required int32 sequence_number = 5;</code>
     * @return Whether the sequenceNumber field is set.
     */
    boolean hasSequenceNumber();
    /**
     * <code>required int32 sequence_number = 5;</code>
     * @return The sequenceNumber.
     */
    int getSequenceNumber();

    /**
     * <code>optional string imsi = 6;</code>
     * @return Whether the imsi field is set.
     */
    boolean hasImsi();
    /**
     * <code>optional string imsi = 6;</code>
     *
     * @return The imsi.
     */
    String getImsi();
    /**
     * <code>optional string imsi = 6;</code>
     * @return The bytes for imsi.
     */
    com.google.protobuf.ByteString
        getImsiBytes();

    /**
     * <code>optional string msisdn = 7;</code>
     * @return Whether the msisdn field is set.
     */
    boolean hasMsisdn();
    /**
     * <code>optional string msisdn = 7;</code>
     *
     * @return The msisdn.
     */
    String getMsisdn();
    /**
     * <code>optional string msisdn = 7;</code>
     * @return The bytes for msisdn.
     */
    com.google.protobuf.ByteString
        getMsisdnBytes();

    /**
     * <code>optional string teid = 8;</code>
     * @return Whether the teid field is set.
     */
    boolean hasTeid();
    /**
     * <code>optional string teid = 8;</code>
     * @return The teid.
     */
    java.lang.String getTeid();
    /**
     * <code>optional string teid = 8;</code>
     * @return The bytes for teid.
     */
    com.google.protobuf.ByteString
        getTeidBytes();

    /**
     * <code>optional string cause = 9;</code>
     * @return Whether the cause field is set.
     */
    boolean hasCause();
    /**
     * <code>optional string cause = 9;</code>
     * @return The cause.
     */
    java.lang.String getCause();
    /**
     * <code>optional string cause = 9;</code>
     * @return The bytes for cause.
     */
    com.google.protobuf.ByteString
        getCauseBytes();

    /**
     * <code>optional string user_location = 10;</code>
     * @return Whether the userLocation field is set.
     */
    boolean hasUserLocation();
    /**
     * <code>optional string user_location = 10;</code>
     * @return The userLocation.
     */
    java.lang.String getUserLocation();
    /**
     * <code>optional string user_location = 10;</code>
     * @return The bytes for userLocation.
     */
    com.google.protobuf.ByteString
        getUserLocationBytes();

    /**
     * <code>optional string bearer_context = 11;</code>
     * @return Whether the bearerContext field is set.
     */
    boolean hasBearerContext();
    /**
     * <code>optional string bearer_context = 11;</code>
     * @return The bearerContext.
     */
    java.lang.String getBearerContext();
    /**
     * <code>optional string bearer_context = 11;</code>
     * @return The bytes for bearerContext.
     */
    com.google.protobuf.ByteString
        getBearerContextBytes();

    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return Whether the dpiIp field is set.
     */
    boolean hasDpiIp();
    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return The dpiIp.
     */
    java.lang.String getDpiIp();
    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return The bytes for dpiIp.
     */
    com.google.protobuf.ByteString
        getDpiIpBytes();
  }
  /**
   * Protobuf type {@code exchange_message_def.ProtMessage}
   */
  public static final class ProtMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:exchange_message_def.ProtMessage)
      ProtMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        ProtMessage.class.getName());
    }
    // Use ProtMessage.newBuilder() to construct.
    private ProtMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    public ProtMessage() {
      timestamp_ = "";
      sourceIp_ = "";
      destIp_ = "";
      messageType_ = "";
      imsi_ = "";
      msisdn_ = "";
      teid_ = "";
      cause_ = "";
      userLocation_ = "";
      bearerContext_ = "";
      dpiIp_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gtpvpair.message.ExchangeProtoMessage.internal_static_exchange_message_def_ProtMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gtpvpair.message.ExchangeProtoMessage.internal_static_exchange_message_def_ProtMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.class, org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timestamp_ = "";
    /**
     * <code>required string timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_IP_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceIp_ = "";
    /**
     * <code>required string source_ip = 2;</code>
     * @return Whether the sourceIp field is set.
     */
    @java.lang.Override
    public boolean hasSourceIp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string source_ip = 2;</code>
     * @return The sourceIp.
     */
    @java.lang.Override
    public java.lang.String getSourceIp() {
      java.lang.Object ref = sourceIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string source_ip = 2;</code>
     * @return The bytes for sourceIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceIpBytes() {
      java.lang.Object ref = sourceIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEST_IP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object destIp_ = "";
    /**
     * <code>required string dest_ip = 3;</code>
     * @return Whether the destIp field is set.
     */
    @java.lang.Override
    public boolean hasDestIp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string dest_ip = 3;</code>
     * @return The destIp.
     */
    @java.lang.Override
    public java.lang.String getDestIp() {
      java.lang.Object ref = destIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dest_ip = 3;</code>
     * @return The bytes for destIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestIpBytes() {
      java.lang.Object ref = destIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageType_ = "";
    /**
     * <code>required string message_type = 4;</code>
     * @return Whether the messageType field is set.
     */
    @java.lang.Override
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string message_type = 4;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message_type = 4;</code>
     * @return The bytes for messageType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 5;
    private int sequenceNumber_ = 0;
    /**
     * <code>required int32 sequence_number = 5;</code>
     * @return Whether the sequenceNumber field is set.
     */
    @java.lang.Override
    public boolean hasSequenceNumber() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 sequence_number = 5;</code>
     * @return The sequenceNumber.
     */
    @java.lang.Override
    public int getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int IMSI_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object imsi_ = "";
    /**
     * <code>optional string imsi = 6;</code>
     * @return Whether the imsi field is set.
     */
    @java.lang.Override
    public boolean hasImsi() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string imsi = 6;</code>
     *
     * @return The imsi.
     */
    @java.lang.Override
    public String getImsi() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imsi_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imsi = 6;</code>
     * @return The bytes for imsi.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImsiBytes() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imsi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSISDN_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object msisdn_ = "";
    /**
     * <code>optional string msisdn = 7;</code>
     * @return Whether the msisdn field is set.
     */
    @java.lang.Override
    public boolean hasMsisdn() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string msisdn = 7;</code>
     *
     * @return The msisdn.
     */
    @java.lang.Override
    public String getMsisdn() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msisdn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msisdn = 7;</code>
     * @return The bytes for msisdn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsisdnBytes() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msisdn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEID_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object teid_ = "";
    /**
     * <code>optional string teid = 8;</code>
     * @return Whether the teid field is set.
     */
    @java.lang.Override
    public boolean hasTeid() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string teid = 8;</code>
     * @return The teid.
     */
    @java.lang.Override
    public java.lang.String getTeid() {
      java.lang.Object ref = teid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string teid = 8;</code>
     * @return The bytes for teid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeidBytes() {
      java.lang.Object ref = teid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAUSE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cause_ = "";
    /**
     * <code>optional string cause = 9;</code>
     * @return Whether the cause field is set.
     */
    @java.lang.Override
    public boolean hasCause() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string cause = 9;</code>
     * @return The cause.
     */
    @java.lang.Override
    public java.lang.String getCause() {
      java.lang.Object ref = cause_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cause_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cause = 9;</code>
     * @return The bytes for cause.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCauseBytes() {
      java.lang.Object ref = cause_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_LOCATION_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userLocation_ = "";
    /**
     * <code>optional string user_location = 10;</code>
     * @return Whether the userLocation field is set.
     */
    @java.lang.Override
    public boolean hasUserLocation() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string user_location = 10;</code>
     * @return The userLocation.
     */
    @java.lang.Override
    public java.lang.String getUserLocation() {
      java.lang.Object ref = userLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userLocation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_location = 10;</code>
     * @return The bytes for userLocation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserLocationBytes() {
      java.lang.Object ref = userLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEARER_CONTEXT_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bearerContext_ = "";
    /**
     * <code>optional string bearer_context = 11;</code>
     * @return Whether the bearerContext field is set.
     */
    @java.lang.Override
    public boolean hasBearerContext() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string bearer_context = 11;</code>
     * @return The bearerContext.
     */
    @java.lang.Override
    public java.lang.String getBearerContext() {
      java.lang.Object ref = bearerContext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bearerContext_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bearer_context = 11;</code>
     * @return The bytes for bearerContext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBearerContextBytes() {
      java.lang.Object ref = bearerContext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bearerContext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DPI_IP_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dpiIp_ = "";
    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return Whether the dpiIp field is set.
     */
    @java.lang.Override
    public boolean hasDpiIp() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return The dpiIp.
     */
    @java.lang.Override
    public java.lang.String getDpiIp() {
      java.lang.Object ref = dpiIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dpiIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dpi_ip = 12;</code>
     * @return The bytes for dpiIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDpiIpBytes() {
      java.lang.Object ref = dpiIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dpiIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequenceNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceIp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, destIp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, messageType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, imsi_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, msisdn_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, teid_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, cause_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, userLocation_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, bearerContext_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, dpiIp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceIp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, destIp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, messageType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, imsi_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, msisdn_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, teid_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, cause_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, userLocation_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, bearerContext_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, dpiIp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gtpvpair.message.ExchangeProtoMessage.ProtMessage)) {
        return super.equals(obj);
      }
      org.gtpvpair.message.ExchangeProtoMessage.ProtMessage other = (org.gtpvpair.message.ExchangeProtoMessage.ProtMessage) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasSourceIp() != other.hasSourceIp()) return false;
      if (hasSourceIp()) {
        if (!getSourceIp()
            .equals(other.getSourceIp())) return false;
      }
      if (hasDestIp() != other.hasDestIp()) return false;
      if (hasDestIp()) {
        if (!getDestIp()
            .equals(other.getDestIp())) return false;
      }
      if (hasMessageType() != other.hasMessageType()) return false;
      if (hasMessageType()) {
        if (!getMessageType()
            .equals(other.getMessageType())) return false;
      }
      if (hasSequenceNumber() != other.hasSequenceNumber()) return false;
      if (hasSequenceNumber()) {
        if (getSequenceNumber()
            != other.getSequenceNumber()) return false;
      }
      if (hasImsi() != other.hasImsi()) return false;
      if (hasImsi()) {
        if (!getImsi()
            .equals(other.getImsi())) return false;
      }
      if (hasMsisdn() != other.hasMsisdn()) return false;
      if (hasMsisdn()) {
        if (!getMsisdn()
            .equals(other.getMsisdn())) return false;
      }
      if (hasTeid() != other.hasTeid()) return false;
      if (hasTeid()) {
        if (!getTeid()
            .equals(other.getTeid())) return false;
      }
      if (hasCause() != other.hasCause()) return false;
      if (hasCause()) {
        if (!getCause()
            .equals(other.getCause())) return false;
      }
      if (hasUserLocation() != other.hasUserLocation()) return false;
      if (hasUserLocation()) {
        if (!getUserLocation()
            .equals(other.getUserLocation())) return false;
      }
      if (hasBearerContext() != other.hasBearerContext()) return false;
      if (hasBearerContext()) {
        if (!getBearerContext()
            .equals(other.getBearerContext())) return false;
      }
      if (hasDpiIp() != other.hasDpiIp()) return false;
      if (hasDpiIp()) {
        if (!getDpiIp()
            .equals(other.getDpiIp())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasSourceIp()) {
        hash = (37 * hash) + SOURCE_IP_FIELD_NUMBER;
        hash = (53 * hash) + getSourceIp().hashCode();
      }
      if (hasDestIp()) {
        hash = (37 * hash) + DEST_IP_FIELD_NUMBER;
        hash = (53 * hash) + getDestIp().hashCode();
      }
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageType().hashCode();
      }
      if (hasSequenceNumber()) {
        hash = (37 * hash) + SEQUENCE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getSequenceNumber();
      }
      if (hasImsi()) {
        hash = (37 * hash) + IMSI_FIELD_NUMBER;
        hash = (53 * hash) + getImsi().hashCode();
      }
      if (hasMsisdn()) {
        hash = (37 * hash) + MSISDN_FIELD_NUMBER;
        hash = (53 * hash) + getMsisdn().hashCode();
      }
      if (hasTeid()) {
        hash = (37 * hash) + TEID_FIELD_NUMBER;
        hash = (53 * hash) + getTeid().hashCode();
      }
      if (hasCause()) {
        hash = (37 * hash) + CAUSE_FIELD_NUMBER;
        hash = (53 * hash) + getCause().hashCode();
      }
      if (hasUserLocation()) {
        hash = (37 * hash) + USER_LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getUserLocation().hashCode();
      }
      if (hasBearerContext()) {
        hash = (37 * hash) + BEARER_CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getBearerContext().hashCode();
      }
      if (hasDpiIp()) {
        hash = (37 * hash) + DPI_IP_FIELD_NUMBER;
        hash = (53 * hash) + getDpiIp().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gtpvpair.message.ExchangeProtoMessage.ProtMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    public void setImsi() {

    }

    /**
     * Protobuf type {@code exchange_message_def.ProtMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:exchange_message_def.ProtMessage)
        org.gtpvpair.message.ExchangeProtoMessage.ProtMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gtpvpair.message.ExchangeProtoMessage.internal_static_exchange_message_def_ProtMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gtpvpair.message.ExchangeProtoMessage.internal_static_exchange_message_def_ProtMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.class, org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.Builder.class);
      }

      // Construct using org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = "";
        sourceIp_ = "";
        destIp_ = "";
        messageType_ = "";
        sequenceNumber_ = 0;
        imsi_ = "";
        msisdn_ = "";
        teid_ = "";
        cause_ = "";
        userLocation_ = "";
        bearerContext_ = "";
        dpiIp_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gtpvpair.message.ExchangeProtoMessage.internal_static_exchange_message_def_ProtMessage_descriptor;
      }

      @java.lang.Override
      public org.gtpvpair.message.ExchangeProtoMessage.ProtMessage getDefaultInstanceForType() {
        return org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.gtpvpair.message.ExchangeProtoMessage.ProtMessage build() {
        org.gtpvpair.message.ExchangeProtoMessage.ProtMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gtpvpair.message.ExchangeProtoMessage.ProtMessage buildPartial() {
        org.gtpvpair.message.ExchangeProtoMessage.ProtMessage result = new org.gtpvpair.message.ExchangeProtoMessage.ProtMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.gtpvpair.message.ExchangeProtoMessage.ProtMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sourceIp_ = sourceIp_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.destIp_ = destIp_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.messageType_ = messageType_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sequenceNumber_ = sequenceNumber_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.imsi_ = imsi_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.msisdn_ = msisdn_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.teid_ = teid_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.cause_ = cause_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.userLocation_ = userLocation_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.bearerContext_ = bearerContext_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.dpiIp_ = dpiIp_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gtpvpair.message.ExchangeProtoMessage.ProtMessage) {
          return mergeFrom((org.gtpvpair.message.ExchangeProtoMessage.ProtMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gtpvpair.message.ExchangeProtoMessage.ProtMessage other) {
        if (other == org.gtpvpair.message.ExchangeProtoMessage.ProtMessage.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          timestamp_ = other.timestamp_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSourceIp()) {
          sourceIp_ = other.sourceIp_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasDestIp()) {
          destIp_ = other.destIp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasMessageType()) {
          messageType_ = other.messageType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasSequenceNumber()) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.hasImsi()) {
          imsi_ = other.imsi_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasMsisdn()) {
          msisdn_ = other.msisdn_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasTeid()) {
          teid_ = other.teid_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasCause()) {
          cause_ = other.cause_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (other.hasUserLocation()) {
          userLocation_ = other.userLocation_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.hasBearerContext()) {
          bearerContext_ = other.bearerContext_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (other.hasDpiIp()) {
          dpiIp_ = other.dpiIp_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasSourceIp()) {
          return false;
        }
        if (!hasDestIp()) {
          return false;
        }
        if (!hasMessageType()) {
          return false;
        }
        if (!hasSequenceNumber()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                timestamp_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sourceIp_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                destIp_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                messageType_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                sequenceNumber_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                imsi_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                msisdn_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                teid_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                cause_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                userLocation_ = input.readBytes();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                bearerContext_ = input.readBytes();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                dpiIp_ = input.readBytes();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string timestamp = 1;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        timestamp_ = getDefaultInstance().getTimestamp();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sourceIp_ = "";
      /**
       * <code>required string source_ip = 2;</code>
       * @return Whether the sourceIp field is set.
       */
      public boolean hasSourceIp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string source_ip = 2;</code>
       * @return The sourceIp.
       */
      public java.lang.String getSourceIp() {
        java.lang.Object ref = sourceIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string source_ip = 2;</code>
       * @return The bytes for sourceIp.
       */
      public com.google.protobuf.ByteString
          getSourceIpBytes() {
        java.lang.Object ref = sourceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string source_ip = 2;</code>
       * @param value The sourceIp to set.
       * @return This builder for chaining.
       */
      public Builder setSourceIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceIp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string source_ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceIp() {
        sourceIp_ = getDefaultInstance().getSourceIp();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string source_ip = 2;</code>
       * @param value The bytes for sourceIp to set.
       * @return This builder for chaining.
       */
      public Builder setSourceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sourceIp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object destIp_ = "";
      /**
       * <code>required string dest_ip = 3;</code>
       * @return Whether the destIp field is set.
       */
      public boolean hasDestIp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string dest_ip = 3;</code>
       * @return The destIp.
       */
      public java.lang.String getDestIp() {
        java.lang.Object ref = destIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dest_ip = 3;</code>
       * @return The bytes for destIp.
       */
      public com.google.protobuf.ByteString
          getDestIpBytes() {
        java.lang.Object ref = destIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dest_ip = 3;</code>
       * @param value The destIp to set.
       * @return This builder for chaining.
       */
      public Builder setDestIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        destIp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required string dest_ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestIp() {
        destIp_ = getDefaultInstance().getDestIp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>required string dest_ip = 3;</code>
       * @param value The bytes for destIp to set.
       * @return This builder for chaining.
       */
      public Builder setDestIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        destIp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object messageType_ = "";
      /**
       * <code>required string message_type = 4;</code>
       * @return Whether the messageType field is set.
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string message_type = 4;</code>
       * @return The messageType.
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message_type = 4;</code>
       * @return The bytes for messageType.
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message_type = 4;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string message_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        messageType_ = getDefaultInstance().getMessageType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string message_type = 4;</code>
       * @param value The bytes for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        messageType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int sequenceNumber_ ;
      /**
       * <code>required int32 sequence_number = 5;</code>
       * @return Whether the sequenceNumber field is set.
       */
      @java.lang.Override
      public boolean hasSequenceNumber() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 sequence_number = 5;</code>
       * @return The sequenceNumber.
       */
      @java.lang.Override
      public int getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>required int32 sequence_number = 5;</code>
       * @param value The sequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNumber(int value) {

        sequenceNumber_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sequence_number = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object imsi_ = "";
      /**
       * <code>optional string imsi = 6;</code>
       * @return Whether the imsi field is set.
       */
      public boolean hasImsi() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string imsi = 6;</code>
       *
       * @return The imsi.
       */
      public String getImsi() {
        java.lang.Object ref = imsi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imsi_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imsi = 6;</code>
       * @return The bytes for imsi.
       */
      public com.google.protobuf.ByteString
          getImsiBytes() {
        java.lang.Object ref = imsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imsi = 6;</code>
       * @param value The imsi to set.
       * @return This builder for chaining.
       */
      public Builder setImsi(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        imsi_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imsi = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImsi() {
        imsi_ = getDefaultInstance().getImsi();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string imsi = 6;</code>
       * @param value The bytes for imsi to set.
       * @return This builder for chaining.
       */
      public Builder setImsiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        imsi_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object msisdn_ = "";
      /**
       * <code>optional string msisdn = 7;</code>
       * @return Whether the msisdn field is set.
       */
      public boolean hasMsisdn() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string msisdn = 7;</code>
       *
       * @return The msisdn.
       */
      public String getMsisdn() {
        java.lang.Object ref = msisdn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msisdn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msisdn = 7;</code>
       * @return The bytes for msisdn.
       */
      public com.google.protobuf.ByteString
          getMsisdnBytes() {
        java.lang.Object ref = msisdn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msisdn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msisdn = 7;</code>
       * @param value The msisdn to set.
       * @return This builder for chaining.
       */
      public Builder setMsisdn(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        msisdn_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msisdn = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsisdn() {
        msisdn_ = getDefaultInstance().getMsisdn();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>optional string msisdn = 7;</code>
       * @param value The bytes for msisdn to set.
       * @return This builder for chaining.
       */
      public Builder setMsisdnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        msisdn_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object teid_ = "";
      /**
       * <code>optional string teid = 8;</code>
       * @return Whether the teid field is set.
       */
      public boolean hasTeid() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string teid = 8;</code>
       * @return The teid.
       */
      public java.lang.String getTeid() {
        java.lang.Object ref = teid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string teid = 8;</code>
       * @return The bytes for teid.
       */
      public com.google.protobuf.ByteString
          getTeidBytes() {
        java.lang.Object ref = teid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string teid = 8;</code>
       * @param value The teid to set.
       * @return This builder for chaining.
       */
      public Builder setTeid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        teid_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional string teid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeid() {
        teid_ = getDefaultInstance().getTeid();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>optional string teid = 8;</code>
       * @param value The bytes for teid to set.
       * @return This builder for chaining.
       */
      public Builder setTeidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        teid_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object cause_ = "";
      /**
       * <code>optional string cause = 9;</code>
       * @return Whether the cause field is set.
       */
      public boolean hasCause() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string cause = 9;</code>
       * @return The cause.
       */
      public java.lang.String getCause() {
        java.lang.Object ref = cause_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cause_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cause = 9;</code>
       * @return The bytes for cause.
       */
      public com.google.protobuf.ByteString
          getCauseBytes() {
        java.lang.Object ref = cause_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cause = 9;</code>
       * @param value The cause to set.
       * @return This builder for chaining.
       */
      public Builder setCause(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cause_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cause = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCause() {
        cause_ = getDefaultInstance().getCause();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>optional string cause = 9;</code>
       * @param value The bytes for cause to set.
       * @return This builder for chaining.
       */
      public Builder setCauseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        cause_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object userLocation_ = "";
      /**
       * <code>optional string user_location = 10;</code>
       * @return Whether the userLocation field is set.
       */
      public boolean hasUserLocation() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional string user_location = 10;</code>
       * @return The userLocation.
       */
      public java.lang.String getUserLocation() {
        java.lang.Object ref = userLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userLocation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_location = 10;</code>
       * @return The bytes for userLocation.
       */
      public com.google.protobuf.ByteString
          getUserLocationBytes() {
        java.lang.Object ref = userLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_location = 10;</code>
       * @param value The userLocation to set.
       * @return This builder for chaining.
       */
      public Builder setUserLocation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userLocation_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_location = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserLocation() {
        userLocation_ = getDefaultInstance().getUserLocation();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_location = 10;</code>
       * @param value The bytes for userLocation to set.
       * @return This builder for chaining.
       */
      public Builder setUserLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        userLocation_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object bearerContext_ = "";
      /**
       * <code>optional string bearer_context = 11;</code>
       * @return Whether the bearerContext field is set.
       */
      public boolean hasBearerContext() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional string bearer_context = 11;</code>
       * @return The bearerContext.
       */
      public java.lang.String getBearerContext() {
        java.lang.Object ref = bearerContext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bearerContext_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bearer_context = 11;</code>
       * @return The bytes for bearerContext.
       */
      public com.google.protobuf.ByteString
          getBearerContextBytes() {
        java.lang.Object ref = bearerContext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bearerContext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bearer_context = 11;</code>
       * @param value The bearerContext to set.
       * @return This builder for chaining.
       */
      public Builder setBearerContext(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bearerContext_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bearer_context = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBearerContext() {
        bearerContext_ = getDefaultInstance().getBearerContext();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>optional string bearer_context = 11;</code>
       * @param value The bytes for bearerContext to set.
       * @return This builder for chaining.
       */
      public Builder setBearerContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bearerContext_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private java.lang.Object dpiIp_ = "";
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @return Whether the dpiIp field is set.
       */
      public boolean hasDpiIp() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @return The dpiIp.
       */
      public java.lang.String getDpiIp() {
        java.lang.Object ref = dpiIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dpiIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @return The bytes for dpiIp.
       */
      public com.google.protobuf.ByteString
          getDpiIpBytes() {
        java.lang.Object ref = dpiIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dpiIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @param value The dpiIp to set.
       * @return This builder for chaining.
       */
      public Builder setDpiIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dpiIp_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearDpiIp() {
        dpiIp_ = getDefaultInstance().getDpiIp();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>optional string dpi_ip = 12;</code>
       * @param value The bytes for dpiIp to set.
       * @return This builder for chaining.
       */
      public Builder setDpiIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        dpiIp_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:exchange_message_def.ProtMessage)
    }

    // @@protoc_insertion_point(class_scope:exchange_message_def.ProtMessage)
    private static final org.gtpvpair.message.ExchangeProtoMessage.ProtMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gtpvpair.message.ExchangeProtoMessage.ProtMessage();
    }

    public static org.gtpvpair.message.ExchangeProtoMessage.ProtMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtMessage>() {
      @java.lang.Override
      public ProtMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gtpvpair.message.ExchangeProtoMessage.ProtMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_message_def_ProtMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exchange_message_def_ProtMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/MessageProto.proto\022\024exchange_mes" +
      "sage_def\"\355\001\n\013ProtMessage\022\021\n\ttimestamp\030\001 " +
      "\002(\t\022\021\n\tsource_ip\030\002 \002(\t\022\017\n\007dest_ip\030\003 \002(\t\022" +
      "\024\n\014message_type\030\004 \002(\t\022\027\n\017sequence_number" +
      "\030\005 \002(\005\022\014\n\004imsi\030\006 \001(\t\022\016\n\006msisdn\030\007 \001(\t\022\014\n\004" +
      "teid\030\010 \001(\t\022\r\n\005cause\030\t \001(\t\022\025\n\ruser_locati" +
      "on\030\n \001(\t\022\026\n\016bearer_context\030\013 \001(\t\022\016\n\006dpi_" +
      "ip\030\014 \001(\tB.\n\024org.gtpvpair.messageB\024Exchan" +
      "geProtoMessageH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_exchange_message_def_ProtMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exchange_message_def_ProtMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exchange_message_def_ProtMessage_descriptor,
        new java.lang.String[] { "Timestamp", "SourceIp", "DestIp", "MessageType", "SequenceNumber", "Imsi", "Msisdn", "Teid", "Cause", "UserLocation", "BearerContext", "DpiIp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
